version: '3'
services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile
    image: cache-server:latest
    container_name: server1
    ports:
      - "9527:8080"
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghaiq
    command: ["./server", "0"]

  server2:
    image: cache-server:latest
    container_name: server2
    ports:
      - "9528:8081"
      - "8001:8001"
    environment:
      - TZ=Asia/Shanghai
    command: ["./server", "1"]

  server3:
    image: cache-server:latest
    container_name: server3
    ports:
      - "9529:8082"
      - "8002:8002"
    environment:
      - TZ=Asia/Shanghai
    command: ["./server", "2"]


